In [2]:
# pip install numpy

In [4]:
mylist = [1, 2, 3]

import numpy as np

arr = np.array(mylist)
print(arr)

[1 2 3]


In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])